version: "2.2"
services:
  ilastik:
    shm_size: '2gb'
    build: 
      context: .
      dockerfile: Dockerfile-dev
      args:
        IMAGE: supervisely/ilastik:1.0.0
    ports:
      - "3333:22"
    volumes:
      - "./data:/data"
